[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4", "setuptools-pipfile>=0.5"]
build-backend = "setuptools.build_meta"

[tool.black]
skip-string-normalization = true

[tool]
setuptools_scm = {}
setuptools-pipfile = 3
